#! /bin/bash
bash uber_ga_original_MountainCarContinuous.sh
bash uber_ga_original_InvertedDoublePendulum.sh
bash uber_ga_original_InvertedPendulum.sh
bash uber_ga_original_InvertedPendulumSwingup.sh
bash uber_ga_original_BipedalWalker.sh
bash uber_ga_original_LunarLanderContinuous.sh





