#! /bin/bash
bash ppo_cmaes_surrogate1_uniform_MountainCarContinuous.sh
bash ppo_cmaes_surrogate1_uniform_InvertedDoublePendulum.sh
bash ppo_cmaes_surrogate1_uniform_InvertedPendulum.sh
bash ppo_cmaes_surrogate1_uniform_InvertedPendulumSwingup.sh
bash ppo_cmaes_surrogate1_uniform_BipedalWalker.sh
bash ppo_cmaes_surrogate1_uniform_LunarLanderContinuous.sh





